# set up all the container

# version of docker compose to use
version: "3.7"

# Containers to be used
services:
    
    # DB container
    db:
        image: postgres:12.2
        environment:
            POSTGRES_USER: cc
            POSTGRES_PASSWORD: pp
            POSTGRES_DB: capstone
        # volume to persistent data
        volumes:
            # <local/path/to/store/data>:<path/inside/container>
            - ./pgdata:/var/lib/postgresql/data
            - ./db/db-create.sql:/docker-entrypoint-initdb.d/init.sql
        
        ports:
            # <local/port>:<container/exposing/port>
            - "5432:5432"
    
    # web server
    web:
        # the pre-built flask server
        image: flask-server:v1
        depends_on:
            - db
        ports:
            - "800:80"
